version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-game-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATA_PATH=/app/data/users.json
      - WEBHOOK_ENABLED=${WEBHOOK_ENABLED:-false}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - WEBHOOK_PORT=${WEBHOOK_PORT:-8443}
      - AI_GATEWAY_API_KEY=${AI_GATEWAY_API_KEY:-}
    volumes:
      - ./data:/app/data
    ports:
      - "${WEBHOOK_PORT:-8443}:${WEBHOOK_PORT:-8443}"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
