# Fly.io configuration for Telegram Bot
app = "telegram-game-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8443
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 8080

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"

[env]
  DATA_PATH = "/app/data/users.json"
  WEBHOOK_ENABLED = "true"
  WEBHOOK_PORT = "8443"
  WEBHOOK_PATH = "/webhook"

[mounts]
  source = "telegram_bot_data"
  destination = "/app/data"
