# Fly.io configuration for Discord Bot
app = "discord-game-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 8080

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"

[env]
  DATA_PATH = "/app/data/users.json"
  WEBHOOK_PORT = "8080"
  WEBHOOK_PATH = "/discord-webhook"
  COMMAND_PREFIX = "!"

[mounts]
  source = "telegram_bot_data"
  destination = "/app/data"
